# Generated by Django 3.0.7 on 2020-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveraportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
